image: docker/compose:latest
stages:
  - build

build:
  stage: build
  tags: [visu-cicd-docker]
  services:
    - docker:dind

  before_script:
    - apk update
    - apk add git make
    - git submodule init
    - git submodule update
    - cp .env.dist .env
    - sed -i 's/POSTGRES_USER=/POSTGRES_USER=gitlab/' .env
    - sed -i 's/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=gitlabpwd/' .env
    - echo "${REGISTRY_PASSWORD}" |docker login -u ${REGISTRY_USER} --password-stdin

  script:
    - make build
    - docker tag juank/geocrud-back:latest juank/geocrud-back:$CI_COMMIT_SHORT_SHA
    - docker tag juank/geocrud-front:latest juank/geocrud-front:$CI_COMMIT_SHORT_SHA
    - docker push juank/geocrud-back:latest
    - docker push juank/geocrud-back:$CI_COMMIT_SHORT_SHA
    - docker push juank/geocrud-front:latest
    - docker push juank/geocrud-front:$CI_COMMIT_SHORT_SHA
