image: docker:stable
stages:
  - e2e-tests

cypress:
  stage: e2e-tests
  tags: [visu-cicd-docker]
  image: docker/compose:latest
  services:
    - docker:dind

  before_script:
    - chown -R 1000:1000 .
    - apk update
    - apk upgrade
    - apk add python3 python3-dev build-base gcc openssl-dev libc-dev make git nodejs curl npm
    - docker info
    - node --version
    - npm --version
    - curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - git submodule init
    - git submodule update
    - cd ./cypress
    - npm install .
    - cd ..

  script:
  - cp .env.dist .env
  - sed -i 's/POSTGRES_USER=/POSTGRES_USER=gitlab/' .env
  - sed -i 's/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=gitlabpwd/' .env
  - /usr/local/bin/docker-compose build
  - /usr/local/bin/docker-compose up -d
  - /usr/local/bin/docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/e2e.json
  - /usr/local/bin/docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/demo.json
