image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base gcc openssl-dev libc-dev make
- curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- chmod +x /usr/local/bin/docker-compose

build:
  stage: build
  script:
  - cp .env.dist .env
  - sed -i 's/POSTGRES_USER=/POSTGRES_USER=gitlab/' .env
  - sed -i 's/POSTGRES_DB=/POSTGRES_DB=gitlab/' .env
  - sed -i 's/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=gitlabpwd/' .env
  - docker-compose build
  - docker-compose up -d
  - docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/e2e.json
  - docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/demo.json