image: docker/compose:latest
stages:
  - build

build:
  stage: build
  tags: [visu-cicd-docker]
  services:
    - docker:dind

  before_script:
    - apk update
    - apk add git
    - git submodule init
    - git submodule update
    - cp .env.dist .env
    - sed -i 's/POSTGRES_USER=/POSTGRES_USER=gitlab/' .env
    - sed -i 's/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=gitlabpwd/' .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker-compose build django
    - docker tag juank/geocrud:latest juank/geocrud:$CI_COMMIT_SHA
    - docker push juank/geocrud:latest
    - docker push juank/geocrud:$CI_COMMIT_SHA
