version: "3.7"
services:
  front:
    image: juank/geocrud-front:latest
    build:
      context: ./front
      dockerfile: ../.docker/Dockerfile.front
      args:
        NODE: 12.16
    depends_on:
      - django
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/:ro
    ports:
    - "${FRONT_PORT}:80"

  django:
    image: juank/geocrud-back:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile.back
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.dev
      - API_DOC_ENABLED=True
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/public/data  # mount public folder to add data / keep media files
      - ./conf/custom.py:/app/src/project/settings/custom.py
      - static:/app/public/static  # django static hidden volume
    depends_on:
      - memcached
      - postgres
      - mbglrenderer
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
