ARG NODE=12.16
FROM node:$NODE

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci
COPY . .
RUN [ "npm", "run", "build" ]

FROM nginx:stable
COPY --from=0 /usr/src/app/build/ /var/www/
WORKDIR /var/www/
