ARG NODE=12.16
FROM node:$NODE as dev

WORKDIR /usr/src/app

COPY package*.json ./
# FIX to use npm 7 with node 12
RUN npm install -g npm
# ENDFIX
RUN npm ci
# FIX to use npm 7 with node 12
RUN npm rebuild node-sass
# ENDFIX
COPY . .
RUN [ "npm", "run", "build" ]

FROM nginx:stable as prod
COPY --from=dev /usr/src/app/build/ /var/www/
WORKDIR /var/www/

HEALTHCHECK CMD curl --fail http://127.0.0.1/ || exit 1
